### ISSUE TITLE
What's the role of use cases?

### ISSUE THREAD

**Issue by RobertB4** [eduardomoroni/react-clean-architecture#3]
> BTW feedbacks are welcome 👍🏽

Saw this in another issue, hope it's ok if I make a new one.

First of all, thanks for this repository! It helped me deepen my understanding of clean architecture.
One thing I don't quite get is the role of use cases. I know what they are supposed to do in clean architecture (implement app specific logic) but in this repository they don't really do anything, they are just a wrapper around services. They don't contain any logic and the classes declared inside the useCases directory don't do anything at all as far as I can tell. I can achieve the same result by implementing the interfaces on services and using services directly, as opposed to passing a service to a use case.
What are they meant to do?

**Comment by eduardomoroni** [comment]
@RobertB4 you're absolutely right, a hard thing about creating this sort of repository is to have an example that is not that hard nor that simple.

> I can achieve the same result by implementing the interfaces on services and using services directly, as opposed to passing a service to a use case.

You could but I think the idea of the architecture per say is to have clear boundaries between entities, even though the only purpose of something is to be the boundary (for the time being). I think that for short living repository applying such architecture doesn't worth it at all. But in the case of an application that will live longer may keep things under control.

I'll try to examplify some iteration on this app and clear should be know we to change, and how to test.

- Feature: Require a valid credit card number during sign up without affecting existing users.
  It's pretty clear that we'll have to add an optional field to User entity and during sign up check if the credit card number is valid.
- Feature: Old users should be asked to update their credit card during sign in.
Looks like I'll need to use the same "functionality" to check wether the credit card number is valid or not. This could be a feature now, a pretty small and well defined one that will be consumed by both sign in and sign up.
- Feature: Don't allow different user to use the same credit card.
I know exactly where I should go to change this, the recently created feature, Once I do it both Sign in and sign up feature will be working accordingly.


I think the overall benefit, IMHO, is to provide a CLEAN and intuitive way to organize your code. The benefit is not to save lines of code, you'll probably right more line of code, but it's OK we're looking for other tradeoff.

Please I didn't want to write a lot of text that might not make any sense, feel free to discuss more about it. It's by discussing that we both learn.

---
https://github.com/eduardomoroni/react-clean-architecture/blob/master/authentication/core/lib/useCases/signUpInteractor.ts#L20
In this example, the User entity doesn't need to have the complexity of verifying existing email. User can and should live decoupled from the fact that currently, the app doesn't allow duplicate emails into the system.

**Comment by eduardomoroni** [comment]
I'm assuming you're OK with the current explanation. I'm closing the issue, feel free to re-open it if needed :)
